---
siteuser: valentine
installpath: "/opt/{{ siteuser }}"
gitrepo: "https://github.com/Manotomo-Alliance-Support-Squad/holo-valentine-2021"
backend_proto: "http"
backend_ip: "10.10.6.41"
backend_port: "80"
